package com.codevelop.androidquizapp

object QuizData {
     val questions = arrayOf(
        "What is an APK in android?",
        "What is the base class for all activities in Android?",
        "What is the entry point for the Android application?",
        "What is the file extension of Android XML files?",
        "Which component is not a part of Android's architecture?",
        "What is the use of the findViewById() method in Android?",
        "Which method is called when the activity is no longer visible to the user?",
        "What is the purpose of the AndroidManifest.xml file?",
        "Which class is used to create a new thread in Android?",
        "What is the purpose of the Intent in Android?",
        "Which method is used to start a new activity in Android?",
        "What is the purpose of the Content Provider in Android?",
        "Which method is called when the user interacts with a widget in Android?",
        "What is the purpose of the AsyncTask in Android?",
        "Which class is used to create a database in Android?",
        "What is the purpose of the ActionBar in Android?",
        "Which method is called when the activity is first created?",
        "What is the purpose of the LayoutInflater in Android?",
        "Which class is used to manage the application's preferences in Android?",
        "What is the purpose of the RecyclerView in Android?",
        "Which method is called when the activity is about to be destroyed?",
        "What is the purpose of the Fragment in Android?",
        "Which method is called when the activity is brought to the foreground?",
        "What is the purpose of the View in Android?",
        "Which class is used to create a service in Android?",
        "What is the purpose of the Bundle in Android?",
        "What is a broadcast receiver in android?",
        "What is the purpose of the ViewModel in Android architecture components?",
        "Which class is used to perform network operations in Android?",
        "What is the purpose of the ConstraintLayout in Android?",
    )

     val options = arrayOf(
        arrayOf("Android packages", "Android pack", "Android packaging kit"),
        arrayOf("Activity", "AppCompatActivity", "FragmentActivity"),
        arrayOf("onCreate()", "onStart()", "MainActivity()"),
        arrayOf(".xml", ".html", ".apk"),
        arrayOf("Content Provider", "Intent", "Resolver"),
        arrayOf("To find a view by name", "To find a view by ID", "To find a view by tag"),
        arrayOf("onPause()", "onDestroy()", "onStop()"),
        arrayOf("It contains the application's code", "It contains the application's resources", "It describes the fundamental characteristics of the app"),
        arrayOf("Thread", "AsyncTask", "Handler"),
        arrayOf("To display a notification", "To perform an inter-component communication", "To store application data"),
        arrayOf("startActivity()", "startNewActivity()", "launchActivity()"),
        arrayOf("To manage the application's data", "To provide content to other applications", "To display content to the user"),
        arrayOf("onClick()", "onInteract()", "onWidgetClick()"),
        arrayOf("To perform background tasks", "To handle user interactions", "To manage application resources"),
        arrayOf("SQLiteOpenHelper", "SQLiteDatabase", "SQLiteManager"),
        arrayOf("To display notifications", "To provide navigation options", "To manage application settings"),
        arrayOf("onStart()", "onCreate()", "onResume()"),
        arrayOf("To load an XML layout file", "To inflate a menu resource", "To create a new Intent"),
        arrayOf("SharedPreferences", "PreferenceManager", "PreferenceActivity"),
        arrayOf("To display a list of items", "To manage application resources", "To handle user interactions"),
        arrayOf("onDestroy()", "onStop()", "onPause()"),
        arrayOf("To manage the application's data", "To provide a modular UI component", "To handle user interactions"),
        arrayOf("onResume()", "onRestart()", "onStart()"),
        arrayOf("To manage the application's data", "To provide a user interface component", "To handle user interactions"),
        arrayOf("Service", "IntentService", "ServiceManager"),
        arrayOf("To store application data", "To pass data between components", "To manage application resources"),
        arrayOf("It will react to broadcast announcements.", "It will do background functionalities as services.", "It will pass the data between activities."),
        arrayOf("To manage the application's preferences", "To handle user interactions", "To store and manage UI-related data"),
        arrayOf("NetworkManager", "AsyncTask", "Retrofit"),
        arrayOf("To create responsive UI designs", "To manage application resources", "To handle user interactions"),
    )

    val correctAnswers = arrayOf(
        2, 0, 0, 0, 2, 1, 2, 2, 0, 1,
        0, 1, 0, 0, 0, 1, 1, 0, 0, 0,
        0, 1, 0, 1, 0, 1, 0, 2, 2, 0)
}